### ISSUE TITLE
Has no attribute 'flatten'

### ISSUE THREAD

**Issue by kuradori** [Coyote-A/ultimate-upscale-for-automatic1111#11]
Hello,
i get a error :) How to fix that? 

-upscale.py", line 513, in run
    init_img = images.flatten(init_img, opts.img2img_background_color)
AttributeError: module 'modules.images' has no attribute 'flatten'

**Comment by DaLizardWizard** [comment]
I just got this too, try updating your A111 repo

**Comment by Coyote-A** [comment]
you should update a111 repo at least to this commit https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/9441c28c947588d756e279a8cd5db6c0b4a8d2e4
