### ISSUE TITLE
What's going on please ? I tried to increase the scale but I got 32 images instead.

### ISSUE THREAD

**Issue by IDRAYNAR** [Coyote-A/ultimate-upscale-for-automatic1111#112]
Hello, I followed the tutorial in faq, but the result is not what I expected, any informations about it please?
<hr>
The image I tried to upscale :

![image](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/assets/75629737/e4563fb6-526f-4510-89cb-d36eb5522221)
<hr>
The settings ;

![image](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/assets/75629737/13d94041-c5c3-4cd8-b36d-282d6fbff275)
<hr>
The result :

![image](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/assets/75629737/107116a7-0639-4859-a7c7-bba32dd68b87)

![image](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/assets/75629737/80525daa-5b51-40ef-b2d0-716290728d3c)

**Comment by andreszs** [comment]
Selecting **Type Chess** and **Tile width 512+Tile Height 512** generates that result.

Every single guide clearly states that all settings beyond the **Upscaler** selection must be left in default values, unless you absolutely know what you are doing. Defaults are as follows:

![image](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/assets/10298071/f9d90511-0657-4594-a746-645582c85d40)

**Comment by Pitpe12** [comment]
![image](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/assets/68826106/3219fec6-8146-4c88-a685-d256ef09c7c0)
@IDRAYNAR make sure denoise strength is at 0.35 or less
Note: This setting is in the img2img settings, not from the extension/script settings

**Comment by IDRAYNAR** [comment]
Thank you all for the answers :)
