### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels, but got 4 channels instead

### ISSUE THREAD

**Issue by kkoepke** [Coyote-A/ultimate-upscale-for-automatic1111#12]
I´m always getting following error on the 2nd or 3rd tile:

RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels, but got 4 channels instead

Tried different settings, 1.5 models, image & tile sizes, updated to latest version.

Any idea?

**Comment by Coyote-A** [comment]
try workaround from this issue https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/issues/3

**Comment by kkoepke** [comment]
This worked. Thank you.
