### ISSUE TITLE
Better positioning of tiles

### ISSUE THREAD

**Issue by alfonslm** [Coyote-A/ultimate-upscale-for-automatic1111#13]
I did just see two tiles overlapping like 80% so guess that they could be placed with equal space to optimize the usage of them and minimize edge artifacts.

**Comment by Coyote-A** [comment]
Can you please add more info? What settings do you use? Can you provide some screenshots?

**Comment by alfonslm** [comment]
Can't remember exactly but it was caused by the tiles being just a bit smaller than the closes N*tile of the image.
So, you should be able to reproduce it with something like `256+256+40=568` tiles of 256 and the last two tiles should overlap more than necessary.
![00427-3980543768-masterpiece, best quality,_car](https://user-images.githubusercontent.com/10770782/212865804-fc8ab1dd-94d6-4fb9-ac36-ef47852a0313.png)
The tiles could be arranged so they are centered on a patern that's '189+189+190=568' and using the extra space for padding that should decrease edge artifacts.
