### ISSUE TITLE
Is it possible to use it in a stand alone script?

### ISSUE THREAD

**Issue by kexul** [Coyote-A/ultimate-upscale-for-automatic1111#145]
Hi @Coyote-A , thanks for your great work, is it possible to use this wonderful algorithm in a stand alone python script which take a image as input and output an image?
Many thanks!

**Comment by mflong23** [comment]
@kexul did you make your own stand alone python script? if so, would you mind sharing?

**Comment by kexul** [comment]
> @kexul did you make your own stand alone python script? if so, would you mind sharing?

Nope, I give up...
