### ISSUE TITLE
Add support of float values in scaling factor

### ISSUE THREAD

**Issue by faisalhr1997** [Coyote-A/ultimate-upscale-for-automatic1111#2]
Currently it's limited to integer numbers. entering float numbers give this error. 
![image](https://user-images.githubusercontent.com/97628039/211190509-1745027b-cad3-4325-93a1-09ac6b565353.png)

**Comment by Coyote-A** [comment]
add in https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/commit/abe8ff07d53a150e0ebe32678751608fc3a86f28
