### ISSUE TITLE
Batch Count and Batch Size broken when using this script

### ISSUE THREAD

**Issue by WalternateBishop** [Coyote-A/ultimate-upscale-for-automatic1111#23]
When the script is enabled setting a batch count or batch size above 1 increases the amount of time it takes to calculate the images however it only outputs a single file at the end.

**Comment by RainehDaze** [comment]
Yeah, it seems to process the same tile multiple times but only retains one

When I tried it out, I was hoping that higher batch size would mean doing multiple tiles in parallel.

**Comment by Jopezzia** [comment]
Yes, batches were not supported before. Now they are at the alpha stage, you can switch to branch batch-processing and test it. Batch count still not work, coz it's not needed and calcs by script
