### ISSUE TITLE
What am I doing results are terrible non related

### ISSUE THREAD

**Issue by FurkanGozukara** [Coyote-A/ultimate-upscale-for-automatic1111#4]
First of all it gives a warning in cmd

**Warning: Bad ui setting value: customscript/ultimate-upscale.py/img2img/Type/value: Linear; Default value "None" will be used instead.**

Here my settings and the results

![image](https://user-images.githubusercontent.com/19240467/211902159-5d96910a-c89e-4ece-8f5f-64ed5bd0592b.png)

results

![image](https://user-images.githubusercontent.com/19240467/211902219-0f255d1a-cd31-40dd-982f-395f7fc9cac5.png)

**Comment by imppresser** [comment]
I do not get warnings but can not get good result. Actually, I think we need more clear guide.

**Comment by imppresser** [comment]
![网页捕获_12-1-2023_4710_127 0 0 1](https://user-images.githubusercontent.com/10281931/211907211-4ce135ce-28b3-4c6e-876b-eae207a88cdb.jpeg)
I do not know what should I do to make the right result.

**Comment by Coyote-A** [comment]
you set very high denoise value. more than 0.7 always totally change picture. i recommend 0.35-0.4 for 512 tile size
<img width="288" alt="image" src="https://user-images.githubusercontent.com/11600962/211911295-67633838-44a8-4d39-8585-32fc3849fa89.png">

**Comment by imppresser** [comment]
> you set very high denoise value. more than 0.7 always totally change picture. i recommend 0.35-0.4 for 512 tile size <img alt="image" width="288" src="https://user-images.githubusercontent.com/11600962/211911295-67633838-44a8-4d39-8585-32fc3849fa89.png">

So, original settings above will effect the extension? Not mention in your "How to use" section.

**Comment by Coyote-A** [comment]
Yes it will effect. I should add it to readme

**Comment by Coyote-A** [comment]
sampling method and steps also will effect

**Comment by imppresser** [comment]
So can I understand it as equivalent to an upscaler extension of the original img2img rather than a mere upscaler extension?

**Comment by Coyote-A** [comment]
Sorry, I didn't quite understand the question. It's developed from in-build "sd upscale" script, but it works through inpaints, instead of a grid of independent tiles. due to this, the content of neighboring tiles is taken into account during redrawing. there are also optional additional passes along the seams for better joining of tiles

**Comment by imppresser** [comment]
![网页捕获_12-1-2023_527_127 0 0 1](https://user-images.githubusercontent.com/10281931/211917146-64d1f091-ffee-4b2a-9dc6-64282c736526.jpeg)
I tried your suggestions, but not work, the output is still not near the original image. It more like a new redraw image to me, not upscale the image.

**Comment by imppresser** [comment]
![image](https://user-images.githubusercontent.com/10281931/211921228-06391134-6d02-4e55-bcf0-f52038ab5855.png)
Switched back to 1.5 and Tile 768, Mask 15, padding 38. The results now are reasonable. However,  it changes the output, I can say it is close to the original image like redraw but not as upscale.

**Comment by Coyote-A** [comment]
I tried this model. I thing it works well. No idea why it makes artifacts for you
![image](https://user-images.githubusercontent.com/11600962/211921580-0c2a9f6d-557c-4ae5-8753-ca772ce38994.png)
![image](https://user-images.githubusercontent.com/11600962/211921618-4b31a4d8-d81b-410c-b6a8-3c065f50a791.png)

**Comment by Coyote-A** [comment]
> 

More denoise value = more changes. You can set 0.2-0.25 if you want to get as close as possible to original image

**Comment by imppresser** [comment]
The variation of the demo in your project is pretty small, same 0.35 denoise.

**Comment by imppresser** [comment]
In the case of my image, I tried 0.2, and the reult is good now, is like a best choice, thanks!

**Comment by Coyote-A** [comment]
> The variation of the demo in your project is pretty small, same 0.35 denoise.

This may depend on the target image size, original image size, image content or sampler. Try different settings. I think it's part of the creative process :)

**Comment by FurkanGozukara** [comment]
how can we keep transparent background with this?

org image

![image](https://user-images.githubusercontent.com/19240467/211930433-b71aa1e4-9942-4089-8df2-54067b961c3b.png)


output

![image](https://user-images.githubusercontent.com/19240467/211930442-41a130da-240d-44f3-ba43-8243045ab4c5.png)

**Comment by Coyote-A** [comment]
i dont think than transparency is supported by stable-diffusion-webui. it fills transparent area with color event without script

**Comment by FurkanGozukara** [comment]
> i dont think that transparency is supported by stable-diffusion-webui. it fills transparent area with color event without script

i see

can you add x/y plot to your script?

because Denoising strength makes huge difference

also do prompts, cfg , sampling have any effect?

what options do affect in what way?

i plan to make a tutorial for this extension so if i can learn everything i can explain

**Comment by Coyote-A** [comment]
> can you add x/y plot to your script?
Not sure. This sounds complicated and is beyond the scope of this script.

> also do prompts, cfg , sampling have any effect?
> 
> what options do affect in what way?

Yes, prompts have effect. In the same way as for img2img. Think of this script as a lot of img2img applied to pieces of a big picture. This also applies to sampling method, cfg, steps and seed. They all has effect. Batch count, batch size and resize mode are ignored. Width and height are have effect when you set "Target size type" to "from img2img settings".

**Comment by Coyote-A** [comment]
I recommend using the same prompt as for lowres original. Or describe important parts of image if you dont have any

**Comment by FurkanGozukara** [comment]
I dont know i am trying prompts etc always looks like same output 🗡️ 
testing on this simple image

![image](https://user-images.githubusercontent.com/19240467/211942558-3b6353fa-4903-4f53-9af9-c3b8c23c2082.png)

**Comment by Coyote-A** [comment]
what settings do you use?

**Comment by FurkanGozukara** [comment]
> what settings do you use?

i am playing various

cfg scale to 30
lots of prompts

![image](https://user-images.githubusercontent.com/19240467/211942806-dfe8843d-48ca-49a5-9f3a-4dd84c9e5460.png)

**Comment by Coyote-A** [comment]
you should get upscaled image with low changes from original with this denoise and tile size. what result do you want to achieve?

**Comment by FurkanGozukara** [comment]
> you should get upscaled image with low changes from original with this denoise and tile size. what result do you want to achieve?

I want to improve color shading if possible

do you think possible? like a more professional shading

e.g.

![image](https://user-images.githubusercontent.com/19240467/211943421-66098731-016d-4944-8de5-143ef861273c.png)


can you write into wiki each option does what?

for example tile size
mask blur
padding

i really want to make a great tutorial for this looks very promising 
what is seams fix
all options 
what is type chess
etc

**Comment by Coyote-A** [comment]
for a better understanding of the script, I recommend enabling the preview of intermediate steps, if you have not already done so

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/11600962/211943602-42f6beea-c064-4acb-9bb0-fa618b3bdb70.png">

**Comment by Coyote-A** [comment]
> I want to improve color shading if possible

if you dont need to upscale image then i think it can be done without script. just put "none" in script field, set denoising strengh to middle (0.45-0.6) and try luck :) also maybe it will be easier with another anime/cartoon model like "anything v3"

**Comment by FurkanGozukara** [comment]
> for a better understanding of the script, I recommend enabling the preview of intermediate steps, if you have not already done so
> 
> <img alt="image" width="1238" src="https://user-images.githubusercontent.com/11600962/211943602-42f6beea-c064-4acb-9bb0-fa618b3bdb70.png">

i dont think so that can explain settings
here the list

type : linear chess none 
tile size
mask blur
padding
Band pass
Half tile offset pass
Half tile offset pass + intersections
Seams fix


also i want to upscale  as well :d

**Comment by Coyote-A** [comment]
> Band pass
> Half tile offset pass
> Half tile offset pass + intersections
> Seams fix

i have description in readme


> tile size

it's size of tile. because if you want to get 2k-4k image, you probably get out of vram. script run through image with small pieces of that size. bigger tile-size = more vram, more time, but less artifacts. 


> mask blur

it is blur of masks used in tile masking. set it to 10-15. increase if you see seams.
 
> padding

how many pixels of neighboring tiles will be taken into account when processing a tile


> type : linear chess none
linear - all tiles processed one by one. column by column, row by row
chess - all tiles processd in chess order. decrease chance of getting artifacts on seams.
none - redraw is disabled. use it when run generation without seam fix, see visible overlays or artifacts on seams and want to run just seam pass. put upscaled image as a source before

**Comment by FurkanGozukara** [comment]
Thanks will test all
