### ISSUE TITLE
After the latest update, this error will appear soon after the start, anyone know how to solve it, thank you, very nice plugin.

### ISSUE THREAD

**Issue by liangzixiaoqiang** [Coyote-A/ultimate-upscale-for-automatic1111#59]
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels, but got 4 channels instead

**Comment by Jopezzia** [comment]
Hi! It's after ui update? Or plugin?

**Comment by liangzixiaoqiang** [comment]
ui

**Comment by liangzixiaoqiang** [comment]
i find it  
setting  
stable diffusion 
√ Apply color correction to the result of the graph to match the original color
closed this ,its work
