### ISSUE TITLE
Add support for this on the Stable Horde

### ISSUE THREAD

**Issue by db0** [Coyote-A/ultimate-upscale-for-automatic1111#8]
I've love to have this upscaler available, along with ESRGAN. Our stable horde worker repo is here: https://github.com/db0/AI-Horde-Worker

**Comment by Coyote-A** [comment]
Hi. This extension is script for automatic1111 stable-diffusion-webui, i don't understand how to add support for stable horde worker. But you are free to copy algorithm in our repo
