### ISSUE TITLE
Runtime error everytime I try to upscale

### ISSUE THREAD

**Issue by TheHiddenOne504** [Coyote-A/ultimate-upscale-for-automatic1111#84]
I get a runtime error. Stops right in the middle of the upscaling process. I tried other scripts like SD upscale, but works just fine.
`RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels, but got 4 channels instead
Time taken: 41.98sTorch active/reserved: 3542/4658 MiB, Sys VRAM: 6799/12288 MiB (55.33%)`
![Screenshot 2023-05-13 030312](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/assets/75408875/2800937d-0b05-4af2-a901-d408779b1314)

It was working fine yesterday. I think it maybe due to auto1111 update. Anyway to fix this?

**Comment by jremb** [comment]
Same issue. It will work fine once, but after that fail every time. Started yesterday.

**Comment by f-rank** [comment]
Mine does upscale two tiles and borks with that same error after the second.

**Comment by Razunter** [comment]
Disable "Apply color correction to img2img results to match original colors" in settings.
