### ISSUE TITLE
https/http protocol is not supported

### ISSUE THREAD

**Issue by paolodalprato** [Coyote-A/ultimate-upscale-for-automatic1111#9]
Same error for http 
GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v https://github.com/Coyote-A/ultimate-upscale-for-automatic1111 E:\SD-DIR\A1111 Web UI Autoinstaller\stable-diffusion-webui\tmp\ultimate-upscale-for-automatic1111 stderr: 'Cloning into 'E:\SD-DIR\A1111 Web UI Autoinstaller\stable-diffusion-webui\tmp\ultimate-upscale-for-automatic1111'... fatal: protocol ' https' is not supported '

![protocol_not_supported](https://user-images.githubusercontent.com/42892131/212050880-89509739-04a0-4925-b838-6bc1bb5bc355.jpg)

**Comment by serhio-k** [comment]
Step 1: Remove the folder if exists 'E:\SD-DIR\A1111 Web UI Autoinstaller\stable-diffusion-webui\tmp\ultimate-upscale-for-automatic1111'
Step 2: Restart WebUI
Step 3: Add this URL for installation: **https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git** and click install

**Comment by paolodalprato** [comment]
Done:
- The folder "ultimate-upscale-for-automatic1111" under tmp folder there was not so my first try was with the new link, failed because there was the folder "ultimate-upscale-for-automatic1111" under extensions folder
- Second try: deleted "ultimate-upscale-for-automatic1111" under extension, install was ok

Thanks for the support!
