### ISSUE TITLE
generate more than one tile job at a time?

### ISSUE THREAD

**Issue by unphased** [Coyote-A/ultimate-upscale-for-automatic1111#97]
For those of us with large VRAMs I would love to be able to queue up or even concurrently run multiple tile renders. I noticed that my GPU utilization fluctuates whenever running upscales because there is a slight delay to do processing after each tile is processed. This is not ideal because heating/cooling cycles are what age computer components. So, assuming it's difficult to drastically reduce the delay before processing the next tile, I hope we can allow tiles to be processed with up to N jobs concurrently (using N times the VRAM presumably) and gain a little bit of speed while pegging the GPU utilization instead of making it spike back down repeatedly.

**Comment by Jopezzia** [comment]
Checkout batch-processing branch, its implemented there
